Traceback (most recent call last):
  File "/cow02/rudenko/colowils/LLMExp/LLM-Exp/Pipeline Tests/evaltest.py", line 51, in <module>
    for batch, labels in dataloader:
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/Miniconda3/envs/LLM/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cow02/rudenko/colowils/LLMExp/LLM-Exp/Pipeline Tests/evaltest.py", line 38, in collate_fn
    inputs = {key: pad_sequence([item[key] for item, _ in batch], batch_first=True) for key in batch[0][0].keys()}
                                                                                               ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys